Fix Docker issue
cenit-io/cenit pull request #2993
Opened 2022-10-06 16:15 UTC by alejandro-kid

I did three changes:
- Change th way of build the container.
- Change script to generate application.yml:
  > Explanation: The awk command iterates through each element of a list and executes its instructions, in each iteration it checks that the corresponding environment variable contains information. Since it is impossible to declare a valid environment variable for the system with the following structure 'Cenit::Admin:default_uri', it is decided to create it from one that is valid and eliminate the other environment variable declared in the file, to be provided by the system globally.
- It necesary when the container run, declare a variable called: ADMIN_UI.

2022-10-07 11:51 UTC, sanchojaf requested changes

2022-10-07 11:51 UTC, sanchojaf commented on Dockerfile
> +CMD ["/bin/bash", "-c", "/var/www/cenit/env.sh; bundle exec unicorn_rails -c config/unicorn.rb"]
keep this file like was before and add this line at the end

2022-10-07 11:51 UTC, sanchojaf commented on env.sh
> +awk -F '=' '{ print $1 ": \"" (ENVIRON["ADMIN_UI"] ? ENVIRON["ADMIN_UI"] : $2) "\"" }' ./application.docker.yml >> ./config/application.yml
remove ./application.docker.yml and just add the end of ./config/application.yml ENVIRON["ADMIN_UI"]

2022-10-07 11:51 UTC, sanchojaf commented on docker-compose.yml
> +      - ADMIN_UI=http://localhost:3002
good

2022-10-07 11:51 UTC, sanchojaf commented on docker-compose.yml
> +      - ADMIN_UI=http://localhost:3002
I suggest naming it CENIT_UI

2022-10-07 11:52 UTC, sanchojaf commented on application.docker.yml
>  'Cenit::Admin:default_uri'=http://localhost:3002
remove this file

2022-10-22 08:24 UTC, alejandro-kid commented
- Delete application.docker.yml: Now the config/application.yml will be create inline using an script when the container run. For this purpose need declared two environment variables HOMEPAGE and CENIT_UI.
  > Note: The main conclusion of all my test is that in application.yml need to have both env variables (HOMEPAGE and Cenit::Admin:default_uri), even if HOMEPAGE is not in it, the platform will not redirect correctly.
- Update docker-compose.yml: Here I deleted the configuration of NGINX. Docker compose is not for productions, so dont have sense configure NGINX, i remove this element to do the file more simple.
- Enable build container in developer branch and redefine tags of container: I think that the best way to resolve a bug is knowin where is it. For this reason I configured a system of tags, the tags of master branch will be latest and a short sha (the first 7 numbers), because with the current tag when a new container is pushed override the previusly. And in developer branch the container will have a tag as following: develop-${SHA}

2022-10-25 14:46 UTC, sanchojaf approved these changes

2022-10-26 06:10 UTC, merged